/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-19 04:46:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.admin.nation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sips.common.lib.util.*;
import sips.common.lib.value.*;
import sips.dept.contents.Nation;
import sips.dept.menu.*;

public final class nation_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("sips.common.lib.util");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("sips.common.lib.value");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("sips.dept.menu");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sips.dept.contents.Nation");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');

	String root_path = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  String formName = "frmBoard"; 
      out.write('\r');
      out.write('\n');

	ParamValue       parmValue = new ParamValue();          
	Nation        nation     = new Nation();
    ResultSetValue   rset      = null;
    
	int    cpage              = (request.getParameter("cpage") == null || "".equals(request.getParameter("cpage"))) ? 0 : Integer.parseInt(request.getParameter("cpage"));   // 현재 페이지
    String searchTarget       = StringUtil.defaultIfEmpty(request.getParameter("searchTarget"), "");	      // 검색 조건 (제목/내용)
    String keyword            = StringUtil.defaultIfEmpty(request.getParameter("keyword"     ), "");        // 검색할 키워드
    String searchFlag         = StringUtil.defaultIfEmpty(request.getParameter("searchFlag"  ), "");        // 검색플래그
    String nation_id       = StringUtil.defaultIfEmpty(request.getParameter("nation_id"), "");
    String modeType           = StringUtil.defaultIfEmpty(request.getParameter("modeType"    ), "ins");
    String b_mode             = StringUtil.defaultIfEmpty(request.getParameter("b_mode"      ), ""); 
    
    String national  = "";
    String use_yn = "";
    String strMsg             = "";
    
    parmValue.put("nation_id"    , nation_id  );
    

    if( !"".equals(nation_id)) {
        rset = nation.getNationInfo(parmValue);
        while( rset.next()){
        	national    = StringUtil.defaultIfEmpty(rset.getString("nation"    ), "");
        	use_yn    = StringUtil.defaultIfEmpty(rset.getString("use_yn"    ), "");
        }
 
        if( "Re".equals(b_mode)) {
            strMsg   = "등록";
            
        } else {
            modeType = "mod";
            strMsg   = "수정";
        }
        
    } else {
        modeType = "ins";
        strMsg   = "등록";
    }	

      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("    /**\r\n");
      out.write("     * 게시물 등록\r\n");
      out.write("     */\r\n");
      out.write("    function goRegitProc () {\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        if (frm.national.value == \"\") {\r\n");
      out.write("            alert(\"국가명을 입력하세요.\");\r\n");
      out.write("            frm.national.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if( confirm(\"");
      out.print(strMsg);
      out.write(" 하시겠습니까?\")) {\r\n");
      out.write("            frm.action   = \"nation_write_proc.jsp\";\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\tfunction goModifyProc (member_cd) { \r\n");
      out.write("    var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("    \r\n");
      out.write("\t    if( confirm(\"수정 하시겠습니까?\")) {\r\n");
      out.write("\t        frm.modeType.value = \"mod\";\r\n");
      out.write("\t        frm.action   = \"nation_write_proc.jsp\";\r\n");
      out.write("\t        frm.submit();\r\n");
      out.write("\t    }\r\n");
      out.write("    }    \r\n");
      out.write("\t\r\n");
      out.write("\t  \r\n");
      out.write("    /**\r\n");
      out.write("     * 게시물 삭제\r\n");
      out.write("     */\r\n");
      out.write("    function goDeleteForm () { \r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        if( confirm(\"비활성화 하시겠습니까?\")) {\r\n");
      out.write("            frm.modeType.value = \"del\";\r\n");
      out.write("            frm.action   = \"nation_write_proc.jsp\";\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("                \r\n");
      out.write("    }    \r\n");
      out.write("    \r\n");
      out.write("    function goList() {\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("        frm.b_mode.value = \"L\";\r\n");
      out.write("        frm.action   = \"");
      out.print( request.getRequestURI() );
      out.write("\";\r\n");
      out.write("        frm.submit();\r\n");
      out.write("    }\r\n");
      out.write("  //-->\r\n");
      out.write("</script>\r\n");
      out.write("<form name=\"");
      out.print(formName);
      out.write("\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"cpage\"        value=\"");
      out.print( cpage       );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"nation_id\" value=\"");
      out.print(nation_id );
      out.write("\">  \r\n");
      out.write("<input type=\"hidden\" name=\"b_mode\"       value=\"");
      out.print(b_mode      );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"modeType\"     value=\"");
      out.print(modeType    );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      \r\n");
      out.write("      <tr>\r\n");
      out.write("        <td valign=\"top\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-top:2px solid #e0e0e0; border-bottom:2px solid #e0e0e0; width:784px;\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">국가명</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\"><input name=\"national\" type=\"text\" value=\"");
      out.print(national);
      out.write("\" class=\"Ttable\" size=\"35\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">비활성화처리</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t\t<select name=use_yn id=use_yn>\r\n");
      out.write("\t\t            <option value=\"y\" ");
      out.print( "y".equals(use_yn) ? "selected" : "" );
      out.write(" >활성화</option>   \r\n");
      out.write("\t\t            <option value=\"n\" ");
      out.print( "n".equals(use_yn) ? "selected" : "" );
      out.write(" >비활성화</option>\r\n");
      out.write("          \t\t</select>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"50\" align=\"center\">\r\n");
      out.write("        ");
 if(modeType.equals("ins")){ 
      out.write("\r\n");
      out.write("            <a href=\"javascript:goRegitProc();\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_up.gif\" alt=\"등록\" /></a>\r\n");
      out.write("         ");
 }else{ 
      out.write("\r\n");
      out.write("            <a href=\"javascript:goModifyProc();\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_modify.gif\" alt=\"수정\" /></a>\r\n");
      out.write("         ");
 } 
      out.write("   \r\n");
      out.write("            <a href=\"javascript:goList();\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_list.gif\" alt=\"목록\" /></a>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("</form>\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
