/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-14 08:04:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.conference.register;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sips.common.lib.util.*;
import sips.common.lib.value.*;
import sips.dept.contents.Member;

public final class id_005ffind_005fpopup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("sips.common.lib.util");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("sips.common.lib.value");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sips.dept.contents.Member");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');

	String root_path = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  String formName = "frmBoard"; 
      out.write('\r');
      out.write('\n');

	ParamValue       parmValue = new ParamValue();          
	Member        member     = new Member();
	ResultSetValue   rset      = null;
	
	String result = "";
	
	String user_id       = StringUtil.defaultIfEmpty(request.getParameter("user_id"), "");
    
    parmValue.put("user_id"    , user_id  );
    
    result = member.getNewId(parmValue);


      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>::MICE::</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/mice/css/Layout.css\"/>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\" src=\"/mice/js/common.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("//레이어 팝업 닫기\r\n");
      out.write("\tfunction closeLayer(IdName){\r\n");
      out.write("\t\tvar pop = parent.document.getElementById(IdName);\r\n");
      out.write("\t\tpop.style.display = \"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("function goRegitProc () {\r\n");
      out.write("    var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    if (frm.admin_user_cd.value == \"\") {\r\n");
      out.write("        alert(\"바인더 등록할 아이디를 입력하세요.\");\r\n");
      out.write("        frm.admin_user_cd.focus();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if( confirm(\"선택 아이디의 바인더를 계속 등록 합니다..\")) {\r\n");
      out.write("        frm.action   = \"binder_user_popup.jsp\";\r\n");
      out.write("        frm.target=\"_parent\";\r\n");
      out.write("        frm.b_mode.value = \"R\";\r\n");
      out.write("        frm.modeType.value = \"popIns\";\r\n");
      out.write("        frm.submit();\r\n");
      out.write("        //parent.location.reload();\r\n");
      out.write("        closeLayer('layerPop2');\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goNoRegitProc (){\r\n");
      out.write("    var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("    \r\n");
      out.write("\tparent.onSetSelectInfo(frm.user_id.value);\r\n");
      out.write("\tcloseLayer('layerPop2');\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goSearch() {\r\n");
      out.write("    var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("    \r\n");
      out.write("    if(frm.user_id.value == \"\")\r\n");
      out.write("    {\r\n");
      out.write("\t     alert(\"아이디를 입력해 주십시오.\");\r\n");
      out.write("\t     frm.user_id.focus();\r\n");
      out.write("\t     return false;\r\n");
      out.write("    }\r\n");
      out.write("    if(frm.user_id.value.length < 6 || frm.user_id.value.length >12 )\r\n");
      out.write("    {\r\n");
      out.write("    \talert(\"회원 아이디는 6 ~ 12자의 영문와 숫자만 사용 할 수 있습니다.\");\r\n");
      out.write("      \tfrm.user_id.fucus();\r\n");
      out.write("      \treturn false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    var myregexp = new RegExp('^[A-Za-z]+[0-9]*$');\r\n");
      out.write("    if(!myregexp.test(frm.user_id.value))\r\n");
      out.write("    {\r\n");
      out.write("\t      alert(\"회원아이디는 영문과 숫자로만 입력이 가능합니다.\");\r\n");
      out.write("\t      frm.user_id.fucus();\r\n");
      out.write("\t      return false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    frmBoard.target=\"_self\";\r\n");
      out.write("\tfrmBoard.action             = \"./id_find_popup.jsp\";\r\n");
      out.write("\tfrmBoard.submit();\r\n");
      out.write("}\r\n");
      out.write("  //-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"");
      out.print(formName);
      out.write("\" method=\"post\">\r\n");
      out.write("<div id=\"main-wrapper1\">\r\n");
      out.write("    <div id=\"main-wrapper\">\r\n");
      out.write("    <div id=\"contents\">\r\n");
      out.write("    <div id=\"layerPopOpen\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"box4\">\r\n");
      out.write("                \t<h3>아이디 중복 체크</h3>          \r\n");
      out.write("                </div>     \r\n");
      out.write("                <!--검색 -->  \r\n");
      out.write("                <div class=\"box3\">\r\n");
      out.write("                \t<input name=\"user_id\" type=\"text\" value=\"");
      out.print( user_id );
      out.write("\" onKeypress=\"if (event.keyCode==13) goSearch();\" class=\"input_box\" size=\"20\">\r\n");
      out.write("\t\t\t            <a href=\"javascript:goSearch();\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_search.gif\" alt=\"검색\" class=\"sbtn1\"/></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--스크롤 테이블 -->               \r\n");
      out.write("                <div class=\"box3\">\r\n");

				if ("".equals(result)){
					if ("".equals(user_id)){
						out.println("검색을 이용해서 다른 아이디를 중복확인하세요.");
					}else{
						out.println("사용가능 아이디입니다. 아이디를 클릭하면 하세요.<br><a href=javascript:goNoRegitProc()>"+user_id+"</a>");
					}
				}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t중복 된 아이디가 존재합니다.\r\n");

				}

      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("                    <!--//테이블 -->\r\n");
      out.write("                </div>          \r\n");
      out.write("                <div class=\"box4\">\r\n");
      out.write("\t\t\t\t\t<span class=\"close\"><a href=\"#\" onclick=\"closeLayer('layerPop2')\" class=\"close\">닫기</a></span>\r\n");
      out.write("                </div>     \r\n");
      out.write("                <!--//검색 -->   \r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>                ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
