/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-14 08:03:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.conference.register;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import sips.common.lib.util.*;
import sips.common.lib.value.*;
import sips.dept.contents.Member;
import sips.dept.contents.Conference;
import sips.dept.contents.Appellation;

public final class register_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("sips.common.lib.util");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("sips.common.lib.value");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sips.dept.contents.Appellation");
    _jspx_imports_classes.add("sips.dept.contents.Member");
    _jspx_imports_classes.add("sips.dept.contents.Conference");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');

	String root_path = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  String formName = "frmBoard"; 
      out.write('\r');
      out.write('\n');

	ParamValue       parmValue = new ParamValue();          
	Member            member     = new Member();
	Conference            conference     = new Conference();
	Appellation            appellation     = new Appellation();
    ResultSetValue   rset2      = null;
    ResultSetValue   rset3      = null;
    ResultSetValue   rset4      = null;
    
	String modeType           = StringUtil.defaultIfEmpty(request.getParameter("modeType"    ), "ins");
    String b_mode             = StringUtil.defaultIfEmpty(request.getParameter("b_mode"      ), ""); 
    String conference_id             = StringUtil.defaultIfEmpty(request.getParameter("conference_id"      ), ""); 
    String conference_name  = "";   
    String strMsg   = "수정";
    String sel_appellation_id     = "";   
    String sel_appellation     = "";   
    String appellation_id     = "";   
    String passwd = "";
    String zipcode = "";
    String nation_id = "";

    modeType = "ins";
    strMsg   = "등록";
    
    rset2 = conference.getConferenceList3();
    rset3 = member.getNationList(parmValue);
    parmValue.put("conference_id"    , conference_id  );
    rset4 = appellation.getAppellationSelectList(parmValue);

      out.write("\t\t\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("    /**\r\n");
      out.write("     * 게시물 등록\r\n");
      out.write("     */\r\n");
      out.write("    function goRegitProc () {\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        if (frm.name.value == \"\") {\r\n");
      out.write("            alert(\"이름을 입력하세요.\");\r\n");
      out.write("            frm.name.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(frm.passwd.value.length < 6 || frm.passwd.value.length >12 )\r\n");
      out.write("        {\r\n");
      out.write("        \talert(\"비밀번호는 6 ~ 12자까지 사용 할 수 있습니다.\");\r\n");
      out.write("          \tfrm.passwd.fucus();\r\n");
      out.write("          \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (frm.passwd.value != frm.repasswd.value) {\r\n");
      out.write("            alert(\"비밀번호가 상이합니다..\");\r\n");
      out.write("            frm.repasswd.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (frm.appellation_id.value == \"\") {\r\n");
      out.write("            alert(\"호칭을 선택해주세요.\");\r\n");
      out.write("            frm.appellation_id.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (frm.handphone1.value == \"\") {\r\n");
      out.write("            alert(\"핸드폰 번호를 입력하세요.\");\r\n");
      out.write("            frm.handphone1.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (frm.handphone2.value == \"\") {\r\n");
      out.write("            alert(\"핸드폰 번호를 입력하세요.\");\r\n");
      out.write("            frm.handphone2.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (frm.handphone3.value == \"\") {\r\n");
      out.write("            alert(\"핸드폰 번호를 입력하세요.\");\r\n");
      out.write("            frm.handphone3.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (frm.email1.value == \"\" || frm.email2.value == \"\") {\r\n");
      out.write("            alert(\"이메일 주소를 입력하세요..\");\r\n");
      out.write("            frm.email1.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (frm.zipcode.value == \"\") {\r\n");
      out.write("            alert(\"우편번호를 입력하세요.\");\r\n");
      out.write("            frm.zipcode.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (frm.address.value == \"\") {\r\n");
      out.write("            alert(\"나머지 주소를 입력하세요.\");\r\n");
      out.write("            frm.address.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if( confirm(\"");
      out.print(strMsg);
      out.write(" 하시겠습니까?\")) {\r\n");
      out.write("            frm.action   = \"register_write_proc.jsp\";\r\n");
      out.write("            frm.encoding = \"multipart/form-data\";\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    function getSpace(cnt) {\r\n");
      out.write("        var spc = \"\";\r\n");
      out.write("        for (i = 0; i < cnt; i++) {\r\n");
      out.write("            spc += \" \";\r\n");
      out.write("        }        \r\n");
      out.write("        return spc;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\t//레이어 팝업 닫기\r\n");
      out.write("\tfunction closeLayer(IdName){\r\n");
      out.write("\t\tvar pop = document.getElementById(IdName);\r\n");
      out.write("\t\tpop.style.display = \"none\";\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("    function id_find( ){\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("  \t\tvar pop = document.getElementById('layerPop2');\r\n");
      out.write("  \t\tdocument.all['moveFrame'].src = './id_find_popup.jsp';\r\n");
      out.write(" \t\t\tpop.style.display = \"block\";\r\n");
      out.write(" \t\t\tpop.style.top =  \"170px\";\r\n");
      out.write(" \t\t\tpop.style.left = \"400px\";\r\n");
      out.write("  \t}\r\n");
      out.write("    function zipcode_find( ){\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("  \t\tvar pop = document.getElementById('layerPop3');\r\n");
      out.write("  \t\tdocument.all['moveFrame2'].src = './zipcode_find_popup.jsp';\r\n");
      out.write(" \t\t\tpop.style.display = \"block\";\r\n");
      out.write(" \t\t\tpop.style.top =  \"170px\";\r\n");
      out.write(" \t\t\tpop.style.left = \"400px\";\r\n");
      out.write("  \t}\r\n");
      out.write("    \r\n");
      out.write("    function onSetSelectInfo(value) {\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("\t\t//값 넣기.\r\n");
      out.write("\t\tfor( var i = 0; i <= frm.elements.length - 1; i++ ){\r\n");
      out.write(" \t\t\tif( frm.elements[i].name == \"user_id\" )\r\n");
      out.write(" \t\t\t{\r\n");
      out.write(" \t\t\t\tfrm.elements[i].value = value;\r\n");
      out.write(" \t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("    function conference_change(obj)\r\n");
      out.write("\t{\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("\t\t//var obj_value = conference_id.value;\r\n");
      out.write("\t\t//alert(obj_value);\r\n");
      out.write("\t\tfrm.target=\"_self\";\r\n");
      out.write("\t\tfrm.b_mode.value = \"W\";\r\n");
      out.write("\t\tfrm.action             = \"./register.jsp\";\r\n");
      out.write("\t\tfrm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("    function email_change(obj){\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("\t\tfrm.email2.value = obj.value;\r\n");
      out.write("      \tfrm.email1.fucus();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  //이미지 확장자 체크\r\n");
      out.write("\tfunction file_check_img(uploadImgObj)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar enableUploadFileExt = [\"bmp\",\"jpg\",\"jpeg\",\"gif\",\"png\"];\r\n");
      out.write("\t\tvar uploadImgObjName = uploadImgObj.value;\r\n");
      out.write("\t\tvar upArrLeng = enableUploadFileExt.length;\r\n");
      out.write("\t\tvar chkExe = uploadImgObjName.split(\".\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar chkFiles = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i=0;i<upArrLeng;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(enableUploadFileExt[i] == chkExe[1].toLowerCase())\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tchkFiles = true;\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!chkFiles)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"JPG, GIF, JPEG, BMP, PNG 파일만 등록 가능합니다.\");\r\n");
      out.write("\t\t\tuploadImgObj.outerHTML = uploadImgObj.outerHTML;\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("  \r\n");
      out.write("\tfunction evKey(el) { \r\n");
      out.write("\t\t   var v = el.value.replace(/[^0-9]/g, \"\"); \r\n");
      out.write("\t\t   if(v.length > 4) v = v.slice(0, 4) + \".\" + v.slice(4); \r\n");
      out.write("\t\t   if(v.length > 7) v = v.slice(0, 7) + \".\" + v.slice(7, 9); \r\n");
      out.write("\t\t   el.value = v; \r\n");
      out.write("\t\t} \r\n");
      out.write("\t\r\n");
      out.write("\tfunction allCheck(){\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("        if (frm.all.checked == true){\r\n");
      out.write("\t        frm.authoriry_1.checked = true;\r\n");
      out.write("\t        frm.authoriry_2.checked = true;\r\n");
      out.write("\t        frm.authoriry_3.checked = true;\r\n");
      out.write("\t        frm.authoriry_4.checked = true;\r\n");
      out.write("\t        frm.authoriry_5.checked = true;\r\n");
      out.write("\t        frm.authoriry_6.checked = true;\r\n");
      out.write("\t        frm.authoriry_7.checked = true;\r\n");
      out.write("\t        frm.authoriry_8.checked = true;\r\n");
      out.write("\t        frm.authoriry_9.checked = true;\r\n");
      out.write("        }else{\r\n");
      out.write("        \tfrm.authoriry_1.checked = false;\r\n");
      out.write("\t        frm.authoriry_2.checked = false;\r\n");
      out.write("\t        frm.authoriry_3.checked = false;\r\n");
      out.write("\t        frm.authoriry_4.checked = false;\r\n");
      out.write("\t        frm.authoriry_5.checked = false;\r\n");
      out.write("\t        frm.authoriry_6.checked = false;\r\n");
      out.write("\t        frm.authoriry_7.checked = false;\r\n");
      out.write("\t        frm.authoriry_8.checked = false;\r\n");
      out.write("\t        frm.authoriry_9.checked = false;\r\n");
      out.write("        }\r\n");
      out.write("\t}\r\n");
      out.write("  //-->\r\n");
      out.write("</script>\r\n");
      out.write("<form name=\"");
      out.print(formName);
      out.write("\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"b_mode\"       value=\"");
      out.print(b_mode      );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"modeType\"     value=\"");
      out.print(modeType    );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"email\"   >\r\n");
      out.write("<input type=\"hidden\" name=\"hidden_address\"   >\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      \r\n");
      out.write("      <tr>\r\n");
      out.write("        <td valign=\"top\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-top:2px solid #e0e0e0; border-bottom:2px solid #e0e0e0; width:784px;\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">컨퍼런스명</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t<select name=\"conference_id\" id=\"conference_id\" onchange=\"conference_change(this)\">\r\n");
      out.write("              \t\t\t<option value=\"0\" >선택</option>\r\n");
      out.write("              \t");

              	String selected = "";
              	while( rset2.next()){
                  	if (conference_id.equals(rset2.getString("conference_id"))){
                  		selected = "selected";
                  	}else{
                  		selected = "";
                  	}
              		out.println("<option value="+rset2.getString("conference_id"    )+"  "+selected+">"+rset2.getString("name"    )+"</option>");            	    
              	}
              	
      out.write("\r\n");
      out.write("              \t</select>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">아이디</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"user_id\" id=\"user_id\" readonly=\"readonly\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"찾아보기\" onclick=\"id_find();\"/>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">이름</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\"><input type=\"text\" name=\"name\" value=\"\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">비밀번호</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\"><input type=\"password\" name=\"passwd\" value=\"\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">비밀번호 확인</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\"><input type=\"password\" name=\"repasswd\" value=\"\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">성별</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\"><input type=\"radio\" name=\"sex\" value=\"male\" checked>남자 \r\n");
      out.write("              <input type=\"radio\" name=\"sex\" value=\"female\">여자</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">소속</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\"><input type=\"text\" name=\"company\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">국가</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              <select name=\"nation_id\">\r\n");
      out.write("              \t");

              	String selected3 = "";
              	while( rset3.next()){
                  	if (nation_id.equals(rset3.getString("nation_id"))){
                  		selected3 = "selected";
                  	}else{
                  		selected3 = "";
                  	}
              		out.println("<option value="+rset3.getString("nation_id"    )+"  "+selected3+">"+rset3.getString("nation"    )+"</option>");            	    
              	}
              	
      out.write("\r\n");
      out.write("              \t\t\r\n");
      out.write("              \t</select>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">호칭</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t<select name=appellation_id id=appellation_id>\r\n");
      out.write("              \t\t\t<option value=\"\" >선택</option>\r\n");

    if(  rset4.row()==0) { 
      out.write("\r\n");
      out.write("                \r\n");
    
    } else {
        while( rset4.next()){
        	sel_appellation_id     = StringUtil.defaultIfEmpty(rset4.getString("appellation_id" ), "");
        	sel_appellation    = StringUtil.defaultIfEmpty(rset4.getString("appellation"), "");

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(sel_appellation_id);
      out.write('"');
      out.write(' ');
      out.print( sel_appellation_id.equals(appellation_id) ? "selected" : "" );
      out.write(' ');
      out.write('>');
      out.print(sel_appellation);
      out.write("</option>\r\n");
      out.write("\t\t\t\r\n");
      } 
    }
    
      out.write("           \r\n");
      out.write("          \t\t</select>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">사진</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t<input name=\"picture\" type=\"file\" onchange=\"file_check_img(this)\">\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">핸드폰</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t\t<select id=\"select_phoneFirst\" name=\"handphone1\" class=\"phone\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"010\">010</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"011\" >011</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"016\" >016</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"017\" >017</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"018\" >018</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"019\" >019</option>\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t-\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"text phone\" name=\"handphone2\" maxlength=\"4\" value=\"\" style=\"width: 40px\"  onkeyup=\"evKey(this)\"  />\r\n");
      out.write("\t\t\t-\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"text phone\" name=\"handphone3\" maxlength=\"4\" value=\"\" style=\"width: 40px\"  onkeyup=\"evKey(this)\"  />\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"first_phone\" value=\"h\"   checked>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">전화번호</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t\t<select id=\"select_phoneFirst\" name=\"phone1\" class=\"phone\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"02\"  >02</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"031\">031</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"032\">032</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"033\">033</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"041\">041</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"042\">042</option>\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"043\">043</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"051\">051</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"052\">052</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"053\">053</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"054\">054</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"055\">055</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"061\">061</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"062\">062</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"063\">063</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"064\">064</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"070\">070</option>\t\t\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0505\">>0505</option>\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t-\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"text phone\" name=\"phone2\" maxlength=\"4\" value=\"\" style=\"width: 40px\"  onkeyup=\"evKey(this)\"  />\r\n");
      out.write("\t\t\t-\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"text phone\" name=\"phone3\" maxlength=\"4\" value=\"\" style=\"width: 40px\"  onkeyup=\"evKey(this)\"  />\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"first_phone\" value=\"p\">\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">이메일</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t<input type=\"text\" class=\"text email\" name=\"email1\"  maxlength =\"20\" value=\"\"  style=\"width: 90px\" />\r\n");
      out.write("\t\t\t\t@\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"text email\" name=\"email2\" id=\"email\"  maxlength =\"20\" value=\"\" style=\"width: 110px\"  />\r\n");
      out.write("\t\t\t\t<select class=\"email_selector\"  onchange=\"email_change(this)\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"chol.com\">chol.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"dreamwiz.com\">dreamwiz.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"empal.com\">empal.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"freechal.com\">freechal.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"hanafos.com\">hanafos.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"hitel.net\">hitel.net</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"hotmail.com\">hotmail.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"korea.com\">korea.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"lycos.co.kr\">lycos.co.kr</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"netian.com\">netian.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"yahoo.co.kr\">yahoo.co.kr</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("              \t\t\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">주소</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t\t<input type=\"text\" name=\"zipcode\" id=\"zipcode\" value=\"\" readonly=\"readonly\"  style=\"width: 50px\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"찾아보기\" onclick=\"zipcode_find();\"/>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"address\" id=\"address\" value=\"\"  style=\"width: 380px\">\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">개인정보 보호</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\"><input type=\"radio\" name=\"question_authority\" value=\"y\" checked>노출\r\n");
      out.write("               <input type=\"radio\" name=\"question_authority\" value=\"n\" >비노출</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"50\" align=\"center\">\r\n");
      out.write("        \t<a href=\"javascript:goRegitProc();\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_up.gif\" alt=\"등록\" /></a>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("</form>\t\t\r\n");
      out.write("\r\n");
      out.write("<!-- 팝업 -->\r\n");
      out.write("<div  id=\"layerPop2\" >\r\n");
      out.write(" <iframe id=\"moveFrame\" frameborder='0' height='100%' width='100%' scrolling='no' src=''></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("<div  id=\"layerPop3\" >\r\n");
      out.write(" <iframe id=\"moveFrame2\" frameborder='0' height='100%' width='100%' scrolling='no' src=''></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("<!--// 팝업 -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
