/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-19 04:50:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.admin.sponsor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sips.common.lib.util.*;
import sips.common.lib.value.*;
import sips.dept.contents.Sponsor;
import sips.dept.contents.Conference;

public final class sponsor_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("sips.common.lib.util");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("sips.common.lib.value");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sips.dept.contents.Conference");
    _jspx_imports_classes.add("sips.dept.contents.Sponsor");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');

	String root_path = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  String formName = "frmBoard"; 
      out.write('\r');
      out.write('\n');

	ParamValue       parmValue = new ParamValue();          
	Sponsor        sponsor     = new Sponsor();
	Conference       conference     = new Conference();
    ResultSetValue   rset      = null;
    ResultSetValue   rset3      = null;

    String user_cd         = (String)session.getAttribute("USER_CD");
    String user_authority         = (String)session.getAttribute("USE_AUTHORITY");
	int    cpage              = (request.getParameter("cpage") == null || "".equals(request.getParameter("cpage"))) ? 0 : Integer.parseInt(request.getParameter("cpage"));   // 현재 페이지
    String searchTarget       = StringUtil.defaultIfEmpty(request.getParameter("searchTarget"), "");	      // 검색 조건 (제목/내용)
    String keyword            = StringUtil.defaultIfEmpty(request.getParameter("keyword"     ), "");        // 검색할 키워드
    String searchFlag         = StringUtil.defaultIfEmpty(request.getParameter("searchFlag"  ), "");        // 검색플래그

    String conference_id             = StringUtil.defaultIfEmpty(request.getParameter("conference_id"      ), ""); 
    String modeType           = StringUtil.defaultIfEmpty(request.getParameter("modeType"    ), "ins");
    String b_mode             = StringUtil.defaultIfEmpty(request.getParameter("b_mode"      ), ""); 
    String sponsor_id             = StringUtil.defaultIfEmpty(request.getParameter("sponsor_id"      ), ""); 
    
    String name  = "";
    String explanation = "";
    String logo    = "";
    String detail_image    = "";
    String strMsg = "";
    String sel_conference_name = "";
    String sel_conference_id = "";
    
    parmValue.put("conference_id"    , conference_id  );
    parmValue.put("sponsor_id"    , sponsor_id  );
    parmValue.put("user_cd"        , user_cd  );  
    parmValue.put("user_authority"        , user_authority  );  

    if( !"".equals(sponsor_id)) {
        rset = sponsor.getSponsorInfo(parmValue);
        while( rset.next()){
        	explanation    = StringUtil.defaultIfEmpty(rset.getString("explanation"    ), "");
        	logo    = StringUtil.defaultIfEmpty(rset.getString("logo"    ), "");
        	detail_image    = StringUtil.defaultIfEmpty(rset.getString("detail_image"    ), "");
        }
 
        if( "Re".equals(b_mode)) {
            strMsg   = "등록";

        } else {
            modeType = "mod";
            strMsg   = "수정";
        }
        
    } else {
        modeType = "ins";
        strMsg   = "등록";
    }	
    rset3 = conference.getConferenceSelectList(parmValue);

      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("    /**\r\n");
      out.write("     * 게시물 등록\r\n");
      out.write("     */\r\n");
      out.write("    function goRegitProc () {\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        if (frm.explanation.value == \"\") {\r\n");
      out.write("            alert(\"스폰서를 입력하세요.\");\r\n");
      out.write("            frm.explanation.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (frm.logo.value == \"\") {\r\n");
      out.write("            alert(\"베너이미지를 등록하세요.\");\r\n");
      out.write("            frm.logo.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (frm.detail_image.value == \"\") {\r\n");
      out.write("            alert(\"상세 이미지를 등록하세요.\");\r\n");
      out.write("            frm.detail_image.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if( confirm(\"");
      out.print(strMsg);
      out.write(" 하시겠습니까?\")) {\r\n");
      out.write("            frm.action   = \"sponsor_write_proc.jsp\";\r\n");
      out.write("            frm.encoding = \"multipart/form-data\";\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\tfunction goModifyProc (member_cd) { \r\n");
      out.write("    var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("    \r\n");
      out.write("\t    if( confirm(\"수정 하시겠습니까?\")) {\r\n");
      out.write("\t        frm.modeType.value = \"mod\";\r\n");
      out.write("\t        frm.action   = \"sponsor_write_proc.jsp\";\r\n");
      out.write("\t        frm.encoding = \"multipart/form-data\";\r\n");
      out.write("\t        frm.submit();\r\n");
      out.write("\t    }\r\n");
      out.write("    }    \r\n");
      out.write("\t\r\n");
      out.write("\t  \r\n");
      out.write("    /**\r\n");
      out.write("     * 게시물 삭제\r\n");
      out.write("     */\r\n");
      out.write("    function goDeleteForm () { \r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        if( confirm(\"삭제 하시겠습니까?\")) {\r\n");
      out.write("            frm.modeType.value = \"del\";\r\n");
      out.write("            frm.action   = \"sponsor_write_proc.jsp\";\r\n");
      out.write("\t        frm.encoding = \"multipart/form-data\";\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("                \r\n");
      out.write("    }    \r\n");
      out.write("    \r\n");
      out.write("    function goList() {\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("        frm.b_mode.value = \"L\";\r\n");
      out.write("        frm.action   = \"");
      out.print( request.getRequestURI() );
      out.write("\";\r\n");
      out.write("        frm.submit();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  //이미지 확장자 체크\r\n");
      out.write("\tfunction file_check_img(uploadImgObj)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar enableUploadFileExt = [\"bmp\",\"jpg\",\"jpeg\",\"gif\",\"png\"];\r\n");
      out.write("\t\tvar uploadImgObjName = uploadImgObj.value;\r\n");
      out.write("\t\tvar upArrLeng = enableUploadFileExt.length;\r\n");
      out.write("\t\tvar chkExe = uploadImgObjName.split(\".\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar chkFiles = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i=0;i<upArrLeng;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(enableUploadFileExt[i] == chkExe[1].toLowerCase())\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tchkFiles = true;\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!chkFiles)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"JPG, GIF, JPEG, BMP, PNG 파일만 등록 가능합니다.\");\r\n");
      out.write("\t\t\tuploadImgObj.outerHTML = uploadImgObj.outerHTML;\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("  //-->\r\n");
      out.write("</script>\r\n");
      out.write("<form name=\"");
      out.print(formName);
      out.write("\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"cpage\"        value=\"");
      out.print( cpage       );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"sponsor_id\" value=\"");
      out.print(sponsor_id );
      out.write("\">  \r\n");
      out.write("<input type=\"hidden\" name=\"b_mode\"       value=\"");
      out.print(b_mode      );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"modeType\"     value=\"");
      out.print(modeType    );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"hidden_logo\"     value=\"");
      out.print(logo    );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"hidden_detail_image\"     value=\"");
      out.print(detail_image    );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("       \r\n");
      out.write("        <td valign=\"top\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-top:2px solid #e0e0e0; border-bottom:2px solid #e0e0e0; width:784px;\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">컨퍼런스</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t\t<select name=conference_id id=conference_id>\r\n");

    if(  rset3.row()==0) { 
      out.write("\r\n");
      out.write("               <option value=\"\">컨퍼런스 없음</option> \r\n");
    
    } else {
        while( rset3.next()){
        	sel_conference_name     = StringUtil.defaultIfEmpty(rset3.getString("name" ), "");
        	sel_conference_id    = StringUtil.defaultIfEmpty(rset3.getString("conference_id"), "");

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(sel_conference_id);
      out.write('"');
      out.write(' ');
      out.print( conference_id.equals(sel_conference_id) ? "selected" : "" );
      out.write(' ');
      out.write('>');
      out.print(sel_conference_name);
      out.write("</option>\r\n");
      out.write("\t\t\t\r\n");
      } 
    }
    
      out.write(" \r\n");
      out.write("          \t\t</select>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">스폰서</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\"><input name=\"explanation\" type=\"text\" value=\"");
      out.print(explanation);
      out.write("\" class=\"Ttable\" size=\"50\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">베너이미지<br>\r\n");
      out.write("              \tiOS : 640 * 96(px)<br>\r\n");
      out.write("              \tiPad : 720 * 98(px)<br>\r\n");
      out.write("              \tAndroid : 640 * 96(px)<br>\r\n");
      out.write("              \t80KB 이하(JPG, PNG)\r\n");
      out.write("              \t</td>\r\n");
      out.write("              \r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              ");

              	if (!"".equals(logo)){
              		out.println("<img src=/mice/upload/sponsor/"+logo+"><br>");
              	}
              
      out.write("\r\n");
      out.write("              <input name=\"logo\" type=\"file\" value=\"\" class=\"Ttable\" size=\"35\" onchange=\"file_check_img(this)\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">상세 이미지</td>\r\n");
      out.write("              \r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              ");

              	if (!"".equals(detail_image)){
              		out.println("<img src=/mice/upload/sponsor/"+detail_image+"><br>");
              	}
              
      out.write("\r\n");
      out.write("              <input name=\"detail_image\" type=\"file\" value=\"\" class=\"Ttable\" size=\"35\" onchange=\"file_check_img(this)\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"50\" align=\"center\">\r\n");
      out.write("        ");
 if(modeType.equals("ins")){ 
      out.write("\r\n");
      out.write("            <a href=\"javascript:goRegitProc();\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_up.gif\" alt=\"등록\" /></a>\r\n");
      out.write("         ");
 }else{ 
      out.write("\r\n");
      out.write("            <a href=\"javascript:goModifyProc();\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_modify.gif\" alt=\"수정\" /></a>\r\n");
      out.write("            <a href=\"javascript:goDeleteForm('");
      out.print( sponsor_id );
      out.write("');\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_del.gif\" alt=\"삭제\" /></a>\r\n");
      out.write("         ");
 } 
      out.write("   \r\n");
      out.write("            <a href=\"javascript:goList();\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_list.gif\" alt=\"목록\" /></a>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("</form>\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
