/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-14 08:17:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.admin.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sips.common.lib.util.*;
import sips.common.lib.value.*;
import sips.dept.contents.Member;

public final class member_005fread_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("sips.common.lib.util");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("sips.common.lib.value");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sips.dept.contents.Member");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String root_path = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  String formName = "frmBoard"; 
      out.write('\r');
      out.write('\n');

	ParamValue       parmValue = new ParamValue();      
	Member            member     = new Member();
   
    ResultSetValue   rset      = null;
    ResultSetValue   rset2      = null;

    String b_mode             = StringUtil.defaultIfEmpty(request.getParameter("b_mode"      ), ""); 
	int    cpage              = (request.getParameter("cpage") == null || "".equals(request.getParameter("cpage"))) ? 0 : Integer.parseInt(request.getParameter("cpage"));   // 현재 페이지
    String searchTarget       = StringUtil.defaultIfEmpty(request.getParameter("searchTarget"),"");	      // 검색 조건 (제목/내용)
    String keyword            = StringUtil.defaultIfEmpty(request.getParameter("keyword"     ),"");        // 검색할 키워드
    String searchFlag         = StringUtil.defaultIfEmpty(request.getParameter("searchFlag"  ),"");        // 검색플래그
    String user_cd         = StringUtil.defaultIfEmpty(request.getParameter("user_cd"  ),"");
    String id     = "";
    String name    = "";
    String sex    = "";
    String company    = "";
    String  nation    = "";
    String title    = "";
    String picture    = "";
    String phone1   = "";
    String phone2  = "";
    String phone3   = "";
    String handphone1   = "";
    String handphone2   = "";
    String handphone3   = "";
    String first_phone   = "";
    String email    = "";
    String address    = "";
    String authoriry_1    = "";
    String authoriry_2    = "";
    String authoriry_3    = "";
    String authoriry_4    = "";
    String authoriry_5    = "";
    String authoriry_6    = "";
    String authoriry_7   = "";
    String authoriry_8    = "";
    String authoriry_9    = "";
    String research_authoriry    = "";
    String question_authority    = "";
    String reg_date    = "";
    String platform    = "";
    String authority = "";
    String conference_name  = "";   
    String appellation_name  = "";   
    String street_address = "";
    String street_address_detail = "";
    String city = "";
    String state = "";
    String postal_code = "";
    String qr_image = "";
  
    String modeType           = "";
    String strMsg             = "";


    boolean isWriter       = false; // 글 작성자인가 아닌가
    
    parmValue.put("user_cd"  , user_cd  );  
    rset = member.getMemberInfo(parmValue);
	while( rset.next()){
		conference_name    = StringUtil.defaultIfEmpty(rset.getString("conference_name"    ), "");
	    id    = StringUtil.defaultIfEmpty(rset.getString("id"    ), "");
	    name    = StringUtil.defaultIfEmpty(rset.getString("name"    ), "");
	    sex    = StringUtil.defaultIfEmpty(rset.getString("sex"    ), "");
	    company    = StringUtil.defaultIfEmpty(rset.getString("company"    ), "");
	    nation    = StringUtil.defaultIfEmpty(rset.getString("nation"    ), "");
	    title    = StringUtil.defaultIfEmpty(rset.getString("title"    ), "");
	    picture    = StringUtil.defaultIfEmpty(rset.getString("picture"    ), "");
	    phone1    = StringUtil.defaultIfEmpty(rset.getString("phone1"    ), "");
	    phone2    = StringUtil.defaultIfEmpty(rset.getString("phone2"    ), "");
	    phone3    = StringUtil.defaultIfEmpty(rset.getString("phone3"    ), "");
	    handphone1    = StringUtil.defaultIfEmpty(rset.getString("handphone1"    ), "");
	    handphone2    = StringUtil.defaultIfEmpty(rset.getString("handphone2"    ), "");
	    handphone3    = StringUtil.defaultIfEmpty(rset.getString("handphone3"    ), "");
	    first_phone    = StringUtil.defaultIfEmpty(rset.getString("first_phone"    ), "");
	    email    = StringUtil.defaultIfEmpty(rset.getString("email"    ), "");
	    address    = StringUtil.defaultIfEmpty(rset.getString("address"    ), "");
	    authoriry_1    = StringUtil.defaultIfEmpty(rset.getString("authoriry_1"    ), "");
	    authoriry_2    = StringUtil.defaultIfEmpty(rset.getString("authoriry_2"    ), "");
	    authoriry_3    = StringUtil.defaultIfEmpty(rset.getString("authoriry_3"    ), "");
	    authoriry_4    = StringUtil.defaultIfEmpty(rset.getString("authoriry_4"    ), "");
	    authoriry_5    = StringUtil.defaultIfEmpty(rset.getString("authoriry_5"    ), "");
	    authoriry_6    = StringUtil.defaultIfEmpty(rset.getString("authoriry_6"    ), "");
	    authoriry_7    = StringUtil.defaultIfEmpty(rset.getString("authoriry_7"    ), "");
	    authoriry_8    = StringUtil.defaultIfEmpty(rset.getString("authoriry_8"    ), "");
	    authoriry_9    = StringUtil.defaultIfEmpty(rset.getString("authoriry_9"    ), "");
	    research_authoriry    = StringUtil.defaultIfEmpty(rset.getString("research_authoriry"    ), "");
	    question_authority    = StringUtil.defaultIfEmpty(rset.getString("question_authority"    ), "");
	    reg_date    = StringUtil.defaultIfEmpty(rset.getString("reg_date"    ), "");
	    platform    = StringUtil.defaultIfEmpty(rset.getString("platform"    ), "");
	    authority    = StringUtil.defaultIfEmpty(rset.getString("authority"    ), "");
	    appellation_name    = StringUtil.defaultIfEmpty(rset.getString("appellation_name"    ), "");
	    street_address    = StringUtil.defaultIfEmpty(rset.getString("street_address"    ), "");
	    street_address_detail    = StringUtil.defaultIfEmpty(rset.getString("street_address_detail"    ), "");
	    city    = StringUtil.defaultIfEmpty(rset.getString("city"    ), "");
	    state    = StringUtil.defaultIfEmpty(rset.getString("state"    ), "");
	    postal_code    = StringUtil.defaultIfEmpty(rset.getString("postal_code"    ), "");
	    qr_image    = StringUtil.defaultIfEmpty(rset.getString("qr_image"    ), "");
	}

      out.write("\t\t\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("    /**\r\n");
      out.write("     * 게시물 수정\r\n");
      out.write("     */\r\n");
      out.write("    function goModifyForm (user_cd ) {        \r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("        frm.user_cd.value = user_cd;\r\n");
      out.write("        frm.target=\"_self\";\r\n");
      out.write("        frm.b_mode.value = \"M\";\r\n");
      out.write("        frm.action = \"");
      out.print(request.getRequestURI());
      out.write("\";\r\n");
      out.write("        frm.submit();\r\n");
      out.write("    }    \r\n");
      out.write("    /**\r\n");
      out.write("     * 게시물 삭제\r\n");
      out.write("     */\r\n");
      out.write("    function goDeleteForm (user_cd) { \r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("\r\n");
      out.write("        if( confirm(\"삭제 하시겠습니까?\")) {\r\n");
      out.write("            frm.user_cd.value = user_cd;\r\n");
      out.write("            frm.modeType.value = \"del\";\r\n");
      out.write("            frm.action   = \"member_write_proc.jsp\";\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("                \r\n");
      out.write("    }    \r\n");
      out.write("\r\n");
      out.write("    /* page 이동 */\r\n");
      out.write("    function goList() {\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("        frm.b_mode.value = \"L\";\r\n");
      out.write("        frm.target=\"_self\";\r\n");
      out.write("        frm.action = \"");
      out.print(request.getRequestURI());
      out.write("\";\r\n");
      out.write("        frm.submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 읽기 페이지로 이동 */\r\n");
      out.write("    function goDisplay(idx) {\r\n");
      out.write("        var frm = document.");
      out.print(formName);
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("        frm.idx.value          = idx;\r\n");
      out.write("        frm.b_mode.value    = \"R\";\r\n");
      out.write("        frm.target=\"_self\";\r\n");
      out.write("        frm.action             = \"");
      out.print( request.getRequestURI() );
      out.write("\";\r\n");
      out.write("        frm.submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("<form name=\"");
      out.print(formName);
      out.write("\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"cpage\"        value=\"");
      out.print( cpage       );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"b_mode\"       value=\"");
      out.print(b_mode      );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"modeType\"     value=\"");
      out.print(modeType    );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"user_cd\"      value=\"");
      out.print(user_cd);
      out.write("\">   \r\n");
      out.write("\t\r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td valign=\"top\">\r\n");
      out.write("           <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-top:2px solid #e0e0e0; border-bottom:2px solid #e0e0e0; width:784px;\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">컨퍼런스</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">");
      out.print(conference_name);
      out.write("</td>\r\n");
      out.write("            </tr>\t\t\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">권한</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(authority);
      out.write("</td>\r\n");
      out.write("            </tr>\t\t\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">아이디</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(id);
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">이름</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(name );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">성별</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(sex);
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">소속</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(company);
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">직책</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(appellation_name);
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">사진</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">\r\n");
      out.write("              \t");

              	if (!"".equals(picture)){
              		out.println("<img src=/mice/upload/member/"+picture+"><br>");
              	}
              
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">핸드폰</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(handphone1);
      out.write('-');
      out.print(handphone2);
      out.write('-');
      out.print(handphone3);
      out.write(' ');
      out.print("h".equals(first_phone)? "대표번호" : "");
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">전화번호</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(phone1);
      out.write('-');
      out.print(phone2);
      out.write('-');
      out.print(phone3);
      out.write(' ');
      out.print("p".equals(first_phone)? "대표번호" : "");
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">이메일</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(email);
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">국가</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(nation);
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">Street address</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t\t");
      out.print(street_address);
      out.write("<br>\r\n");
      out.write("              \t\t");
      out.print(street_address_detail);
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">City</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t\t");
      out.print(city);
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">State</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t\t");
      out.print(state);
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"210\" class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">Postal Code</td>\r\n");
      out.write("              <td width=\"574\" style=\"padding-left:20px;\">\r\n");
      out.write("              \t\t");
      out.print(postal_code);
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">QR 코드</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">\r\n");
      out.write("              \t");

              	if (!"".equals(qr_image)){
              		out.println("<img src=/mice/upload/qr/"+qr_image+"><br>");
              	}
              
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">메뉴권한</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(authoriry_1);
      out.write(',');
      out.write(' ');
      out.print(authoriry_2);
      out.write(',');
      out.write(' ');
      out.print(authoriry_3);
      out.write(',');
      out.write(' ');
      out.print(authoriry_4);
      out.write(',');
      out.write(' ');
      out.print(authoriry_5);
      out.write("<br> ");
      out.print(authoriry_6);
      out.write(',');
      out.write(' ');
      out.print(authoriry_7);
      out.write(',');
      out.write(' ');
      out.print(authoriry_8);
      out.write(',');
      out.write(' ');
      out.print(authoriry_9);
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">설문조사 권한</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(("n".equals(research_authoriry)? "비노출":"노출"));
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">개인정보 보호</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(("n".equals(question_authority)? "비노출":"노출"));
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">가입일</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(reg_date);
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"bbbg\" style=\"padding-left:20px; font-weight:bold;\">모바일OS</td>\r\n");
      out.write("              <td style=\"padding-left:20px;\">");
      out.print(platform);
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"50\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t <a href=\"javascript:goList();\"><img src=\"/dhsp/images/bt_list.gif\" alt=\"목록\" /></a>\r\n");
      out.write("                      <a href=\"javascript:goModifyForm('");
      out.print( user_cd );
      out.write("');\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_modify.gif\" alt=\"수정\" /></a>                   \r\n");
      out.write("                      <a href=\"javascript:goDeleteForm('");
      out.print( user_cd );
      out.write("');\"><img src=\"");
      out.print(root_path);
      out.write("/images/bt_del.gif\" alt=\"삭제\" /></a>    \r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>      \r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</form>\t\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
