/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-14 07:52:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sips.common.lib.value.*;
import sips.common.lib.util.*;
import sips.dept.contents.Banner;

public final class banner_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("sips.common.lib.util");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("sips.common.lib.value");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sips.dept.contents.Banner");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    ParamValue     parmValue = new ParamValue(); 
	Banner         banner     = new Banner();
    ResultSetValue rset      = null;
    ResultSetValue rsetP      = null;


    String banner_1 = "";
    String banner_2 = "";
    String banner_3 = "";
    String banner_4 = "";
    String banner_5 = "";
    String banner_6 = "";
    String banner_7 = "";
    String banner_8 = "";
    String banner_9 = "";
    String banner_10 = "";
    String banner_11 = "";
    String landing_url_1 = "";
    String landing_url_2 = "";
    String landing_url_3 = "";
    String landing_url_4 = "";
    String landing_url_5 = "";
    String landing_url_6 = "";
    String landing_url_7 = "";
    String landing_url_8 = "";
    String landing_url_9 = "";
    String landing_url_10 = "";
    String landing_url_11 = "";

    String  conference_id     = request.getParameter("conference_id");
    
    parmValue.put("conference_id", conference_id);
    rset = banner.getBannerInfoXML(parmValue);

    if(rset.next()) {
    	banner_1 = rset.getString("banner_1");
    	banner_2 = rset.getString("banner_2");
    	banner_3 = rset.getString("banner_3");
    	banner_4 = rset.getString("banner_4");
    	banner_5 = rset.getString("banner_5");
    	banner_6 = rset.getString("banner_6");
    	banner_7 = rset.getString("banner_7");
    	banner_8 = rset.getString("banner_8");
    	banner_9 = rset.getString("banner_9");
    	banner_10 = rset.getString("banner_10");
    	banner_11 = rset.getString("banner_11");
    	landing_url_1 = rset.getString("landing_url_1");
    	landing_url_2 = rset.getString("landing_url_2");
    	landing_url_3 = rset.getString("landing_url_3");
    	landing_url_4 = rset.getString("landing_url_4");
    	landing_url_5 = rset.getString("landing_url_5");
    	landing_url_6 = rset.getString("landing_url_6");
    	landing_url_7 = rset.getString("landing_url_7");
    	landing_url_8 = rset.getString("landing_url_8");
    	landing_url_9 = rset.getString("landing_url_9");
    	landing_url_10 = rset.getString("landing_url_10");
    	landing_url_11 = rset.getString("landing_url_11");
    }

      out.write("<?xml version=\"1.0\" encoding=\"utf-8\"?> \r\n");
      out.write("<ROOT>\r\n");
      out.write("\t<BANNER>");

  			if (!"".equals(banner_1)){
  			
      out.write("<MAIN_BANNER>/mice/upload/banner/");
      out.print(banner_1);
      out.write("</MAIN_BANNER>\r\n");
      out.write("  \t\t<MAIN_LANDING_URL>");
      out.print(landing_url_1);
      out.write("</MAIN_LANDING_URL>\r\n");
      out.write("  \t\t");

  			}
			if (!"".equals(banner_2)){
  		
      out.write("<AGENDA_BANNER>/mice/upload/banner/");
      out.print(banner_2);
      out.write("</AGENDA_BANNER>\r\n");
      out.write("\t  \t\t<AGENDA_LANDING_URL>");
      out.print(landing_url_2);
      out.write("</AGENDA_LANDING_URL>\r\n");
      out.write("\t  \t\t");

  			} 
  			if (!"".equals(banner_3)){
  		
      out.write("<BINDER_BANNER>/mice/upload/banner/");
      out.print(banner_3);
      out.write("</BINDER_BANNER>\r\n");
      out.write("  \t\t<BINDER_LANDING_URL>");
      out.print(landing_url_3);
      out.write("</BINDER_LANDING_URL>\r\n");
      out.write("  \t\t");

  			} 
  			if (!"".equals(banner_4)){
  		
      out.write("<SEARCH_BANNER>/mice/upload/banner/");
      out.print(banner_4);
      out.write("</SEARCH_BANNER>\r\n");
      out.write("  \t\t<SEARCH_LANDING_URL>");
      out.print(landing_url_4);
      out.write("</SEARCH_LANDING_URL>\r\n");
      out.write("  \t\t");

  			} 
  			if (!"".equals(banner_5)){
  		
      out.write("<MASSAGE_BANNER>/mice/upload/banner/");
      out.print(banner_5);
      out.write("</MASSAGE_BANNER>\r\n");
      out.write("  \t\t<MASSAGE_LANDING_URL>");
      out.print(landing_url_5);
      out.write("</MASSAGE_LANDING_URL>\r\n");
      out.write("  \t\t");

  			} 
  			if (!"".equals(banner_6)){
  		
      out.write("<MYBRIEFACASE_BANNER>/mice/upload/banner/");
      out.print(banner_6);
      out.write("</MYBRIEFACASE_BANNER>\r\n");
      out.write("  \t\t<MYBRIEFACASE_LANDING_URL>");
      out.print(landing_url_6);
      out.write("</MYBRIEFACASE_LANDING_URL>\r\n");
      out.write("  \t\t");

  			} 
  			if (!"".equals(banner_7)){
  		
      out.write("<MAP_BANNER>/mice/upload/banner/");
      out.print(banner_7);
      out.write("</MAP_BANNER>\r\n");
      out.write("  \t\t<MAP_LANDING_URL>");
      out.print(landing_url_7);
      out.write("</MAP_LANDING_URL>\r\n");
      out.write("  \t\t");

  			} 
  			if (!"".equals(banner_8)){
  		
      out.write("<RESEARCH_BANNER>/mice/upload/banner/");
      out.print(banner_8);
      out.write("</RESEARCH_BANNER>\r\n");
      out.write("  \t\t<RESEARCH_LANDING_URL>");
      out.print(landing_url_8);
      out.write("</RESEARCH_LANDING_URL>\r\n");
      out.write("  \t\t");

  			} 
  			if (!"".equals(banner_9)){
  		
      out.write("<CONFIG_BANNER>/mice/upload/banner/");
      out.print(banner_9);
      out.write("</CONFIG_BANNER>\r\n");
      out.write("  \t\t<CONFIG_LANDING_URL>");
      out.print(landing_url_9);
      out.write("</CONFIG_LANDING_URL>\r\n");
      out.write("  \t\t");

  			} 
  			if (!"".equals(banner_10)){
  		
      out.write("<BARCODE_BANNER>/mice/upload/banner/");
      out.print(banner_10);
      out.write("</BARCODE_BANNER>\r\n");
      out.write("  \t\t<BARCODE_LANDING_URL>");
      out.print(landing_url_10);
      out.write("</BARCODE_LANDING_URL>\r\n");
      out.write("  \t\t");

  			} 
  			if (!"".equals(banner_11)){
  		
      out.write("<INFOMATION_BANNER>/mice/upload/banner/");
      out.print(banner_11);
      out.write("</INFOMATION_BANNER>\r\n");
      out.write("  \t\t<INFOMATION_LANDING_URL>");
      out.print(landing_url_11);
      out.write("</INFOMATION_LANDING_URL>\r\n");
      out.write("  \t\t");

  			} 
  		
      out.write("\r\n");
      out.write("  \t</BANNER>\r\n");
      out.write("</ROOT>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
