/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-14 08:21:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sips.common.lib.value.*;
import sips.common.lib.util.*;
import sips.dept.contents.Member;

public final class mybusinesscard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("sips.common.lib.util");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("sips.common.lib.value");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sips.dept.contents.Member");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    ParamValue     parmValue = new ParamValue(); 
	Member         member     = new Member();
    ResultSetValue rset      = null;
    ResultSetValue rsetP      = null;


    String name = "";
    String company = "";
    String appellation_id = "";
    String appellation_name = "";
    String phone1 = "";
    String phone2 = "";
    String phone3 = "";
    String email = "";
    String picture = "";
    String street_address = "";
    String street_address_detail = "";
    String city = "";
    String state = "";
    String postal_code = "";
    String businesscard_share = "";
    String nation = "";
    String nation_id = "";

    String  user_cd     = request.getParameter("user_cd");
    
    parmValue.put("user_cd", user_cd);
    rset = member.getMemberInfo(parmValue);

    if(rset.next()) {
    	name = rset.getString("name");
    	company = rset.getString("company");
    	appellation_id = rset.getString("appellation_id");
    	appellation_name = rset.getString("appellation_name");
    	email = rset.getString("email");
    	picture = rset.getString("picture");
    	street_address = rset.getString("street_address");
    	street_address_detail = rset.getString("street_address_detail");
    	city = rset.getString("city");
    	state = rset.getString("state");
    	postal_code = rset.getString("postal_code");
    	businesscard_share = rset.getString("businesscard_share");
    	nation = rset.getString("nation");
    	nation_id = rset.getString("nation_id");
    	
    	if ("h".equals(rset.getString("first_phone"))){
    		phone1 = rset.getString("handphone1");
        	phone2 = rset.getString("handphone2");
        	phone3 = rset.getString("handphone3");
    	}else{
    		phone1 = rset.getString("phone1");
        	phone2 = rset.getString("phone2");
        	phone3 = rset.getString("phone3");
    	}
    }

      out.write("<?xml version=\"1.0\" encoding=\"utf-8\"?> \r\n");
      out.write("<ROOT>\r\n");
      out.write("\t<BUSINESS_CARD>\r\n");
      out.write("  \t\t<USER_NAME>");
      out.print(name);
      out.write("</USER_NAME>\r\n");
      out.write("  \t\t<COMPANY>");
      out.print(company);
      out.write("</COMPANY>\r\n");
      out.write("  \t\t<APPELLATION_ID>");
      out.print(appellation_id);
      out.write("</APPELLATION_ID>\r\n");
      out.write("  \t\t<APPELLATION_NAME>");
      out.print(appellation_name);
      out.write("</APPELLATION_NAME>\r\n");
      out.write("  \t\t<EMAIL>");
      out.print(email);
      out.write("</EMAIL>\r\n");
      out.write("  \t\t<STREET_ADDRESS>");
      out.print(street_address);
      out.write("</STREET_ADDRESS>\r\n");
      out.write("  \t\t<STREET_ADDRESS_DETAIL>");
      out.print(street_address_detail);
      out.write("</STREET_ADDRESS_DETAIL>\r\n");
      out.write("  \t\t<CITY>");
      out.print(city);
      out.write("</CITY>\r\n");
      out.write("  \t\t<STATE>");
      out.print(state);
      out.write("</STATE>\r\n");
      out.write("  \t\t<POSTAL_CODE>");
      out.print(postal_code);
      out.write("</POSTAL_CODE>\r\n");
      out.write("  \t\t<PHONE_1>");
      out.print(phone1);
      out.write("</PHONE_1>\r\n");
      out.write("  \t\t<PHONE_2>");
      out.print(phone2);
      out.write("</PHONE_2>\r\n");
      out.write("  \t\t<PHONE_3>");
      out.print(phone3);
      out.write("</PHONE_3>\r\n");
      out.write("  \t\t<PICTURE>/mice/upload/member/");
      out.print(picture);
      out.write("</PICTURE>\r\n");
      out.write("  \t\t<BUSINESSCARD_SHARE>");
      out.print(businesscard_share);
      out.write("</BUSINESSCARD_SHARE>\r\n");
      out.write("  \t\t<NATION>");
      out.print(nation);
      out.write("</NATION>\r\n");
      out.write("  \t\t<NATION_ID>");
      out.print(nation_id);
      out.write("</NATION_ID>\r\n");
      out.write("  \t</BUSINESS_CARD>\r\n");
      out.write("</ROOT>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
