/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-19 05:06:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import sips.common.lib.value.*;
import sips.common.lib.util.*;
import sips.dept.contents._Member;
import org.apache.commons.fileupload.servlet.*;
import org.apache.commons.fileupload.disk.*;
import org.apache.commons.fileupload.*;
import java.io.*;

public final class user_005finfo_005fupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("sips.common.lib.util");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("sips.common.lib.value");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("org.apache.commons.fileupload");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.apache.commons.fileupload.servlet");
    _jspx_imports_packages.add("org.apache.commons.fileupload.disk");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sips.dept.contents._Member");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    ParamValue     parmValue = new ParamValue(); 
	_Member         member     = new _Member();
    
    String user_cd       = "";
    String  name      = "";
    String  company      = "";
    String  appellation_id       = "";
    String phone1   = "";
    String phone2  = "";
    String phone3   = "";
    String  email      = "";
    String street_address = "";
    String street_address_detail = "";
    String city = "";
    String state = "";
    String postal_code = "";
    String nation_id = "";
    String  picture    = "";
    int rtl =  0;
    String rtlMsg = "";
    String flag = "false";
    
//System.out.println("authoriry_3----------->"+authoriry_3);    	
    int    cnt = 0;
    int    cnt2 = 0;
    boolean  isOk = true;
	
	String originSavePath = request.getRealPath("\\")+"upload\\member\\";			//저장될 경로
	
	File uploadFile = null;
	int idx = 0;
	String fileName = "";
	String tmpFileName = "";
	String thumbFileName = "";
	String[] strExt;	//파일을 파일명과 확장자 분리.
	String Ext="";		//확장자명
	
	//이미지 파일 체크확장자
	String imgExt = "jpg, JPG, jpeg, JPEG, gif, GIF, bmp, BMP, png, PNG";
	
		try {
			if(FileUpload.isMultipartContent(request)) {
				DiskFileUpload fileupload = new DiskFileUpload();								//메모리에 저장
				fileupload.setSizeMax(1024 * 1024 * 10);										//최대 10M까지 업로드 가능.
				fileupload.setHeaderEncoding("UTF-8");
				
				if(request.getContentLength() < fileupload.getSizeMax()) {
					List<Object> fileItemList = fileupload.parseRequest(request);				//파일 item만 리턴.
					int size = fileItemList.size();
					int j = 0;
					for(int i=0;i < size;i++) {
						FileItem fileitem = (FileItem) fileItemList.get(i); 
						tmpFileName = "";
						if(fileitem.isFormField()){												//파라미터일 경우 true
							if (fileitem.getFieldName().equals("name"))name = fileitem.getString("UTF-8");	
							if (fileitem.getFieldName().equals("company"))company = fileitem.getString("UTF-8");	
							if (fileitem.getFieldName().equals("appellation_id"))appellation_id = fileitem.getString("UTF-8");	
							if (fileitem.getFieldName().equals("phone1"))phone1 = fileitem.getString("UTF-8");		
							if (fileitem.getFieldName().equals("phone2"))phone2 = fileitem.getString("UTF-8");		
							if (fileitem.getFieldName().equals("phone3"))phone3 = fileitem.getString("UTF-8");			
							if (fileitem.getFieldName().equals("email"))email = fileitem.getString("UTF-8");	
							if (fileitem.getFieldName().equals("street_address"))street_address = fileitem.getString("UTF-8");	
							if (fileitem.getFieldName().equals("street_address_detail"))street_address_detail = fileitem.getString("UTF-8");	
							if (fileitem.getFieldName().equals("city"))city = fileitem.getString("UTF-8");	
							if (fileitem.getFieldName().equals("state"))state = fileitem.getString("UTF-8");	
							if (fileitem.getFieldName().equals("postal_code"))postal_code = fileitem.getString("UTF-8");
							if (fileitem.getFieldName().equals("nation_id"))nation_id = fileitem.getString("UTF-8");
							if (fileitem.getFieldName().equals("user_cd"))user_cd = fileitem.getString("UTF-8");
						} else {
							if (!(fileitem.getName()).equals("")) {
								if(fileitem.getSize() > 0) {
									idx = fileitem.getName().lastIndexOf("\\");					//getname()은 경로를 다 가져오기 때문에 lastindexof로 잘라냄.
									
									if(idx == 1)
									{
										idx = fileitem.getName().lastIndexOf("/");								
									}
									fileName = fileitem.getName().substring(idx + 1);
									
									if (!fileName.equals("")) {
										int pos = fileName.lastIndexOf(".");
										Ext = fileName.substring(pos+1);	//파일명과 확장자명 분리
										
										if (imgExt.indexOf(Ext) == -1 )
										{
											rtlMsg = "GIF,JPG,JPEG,PNG,BMP 확장자만 업로드 가능합니다.";
											out.println("<?xml version='1.0' encoding='utf-8'?>"); 
											out.println("<ROOT>"); 
											out.println("	<BUSINESSCARD_SHARE>"); 
											out.println("  		<FLAG>false</FLAG>"); 
											out.println("  		<MASSEGE>"+rtlMsg+"</MASSEGE>"); 
											out.println("  	</BUSINESSCARD_SHARE>"); 
											out.println("</ROOT>"); 
											if(true) return;
										}
									}
									
									String upload_time = ""+System.currentTimeMillis();
									tmpFileName = upload_time +"." + Ext;
									
									DateUtil.sleep(10);
									
									//실질적인 저장 부분.
									uploadFile = new File(originSavePath, tmpFileName);
									fileitem.write(uploadFile);
									
									if(fileitem.getFieldName().equals("picture")) {
										picture = tmpFileName;
									}
								}
							}
						}
					}
					 System.out.println("picture------------>"+picture);
					

				} else {
					int overSize = (request.getContentLength() / 1000000);
					rtlMsg = "파일의 크기는 10MB까지 입니다. 올리신 파일 용량은"+overSize+"MB입니다";
					out.println("<?xml version='1.0' encoding='utf-8'?>"); 
					out.println("<ROOT>"); 
					out.println("	<BUSINESSCARD_SHARE>"); 
					out.println("  		<FLAG>false</FLAG>"); 
					out.println("  		<MASSEGE>"+rtlMsg+"</MASSEGE>"); 
					out.println("  	</BUSINESSCARD_SHARE>"); 
					out.println("</ROOT>"); 
					if(true) return;
				}
			} else {
				user_cd = request.getParameter("user_cd");
			}
		} catch(Exception e) {
			
		}
		parmValue.put("name"    , name    );
	    parmValue.put("email"    , email    );
	    parmValue.put("company"       , company      );
	    parmValue.put("appellation_id"        , appellation_id        );      
	    parmValue.put("phone1"        , phone1        );          
	    parmValue.put("phone2"        , phone2        );          
	    parmValue.put("phone3"        , phone3        );          
	    parmValue.put("street_address"        , street_address        );        
	    parmValue.put("street_address_detail"        , street_address_detail        );       
	    parmValue.put("city"        , city        );       
	    parmValue.put("state"        , state        );       
	    parmValue.put("postal_code"        , postal_code        );      
	    parmValue.put("nation_id"        , nation_id        );      
	    parmValue.put("picture"        , picture        );       
	    parmValue.put("user_cd"        , user_cd        );    
	    
	    //System.out.println("user_cd------------>"+user_cd);
	         
    try {	   
        if( isOk ) {
        	rtl = member.memberModify(parmValue);
        	if (rtl == 1)
        		flag = "success";
        } 
    }
    catch (Exception e) {
        System.out.println(e.toString());
        out.println(e.toString());
        e.printStackTrace();
    }   

      out.write("<?xml version=\"1.0\" encoding=\"utf-8\"?> \r\n");
      out.write("<ROOT>\r\n");
      out.write("\t<BUSINESSCARD_UPDATE>\r\n");
      out.write("  \t\t<FLAG>");
      out.print(flag);
      out.write("</FLAG>\r\n");
      out.write("  \t</BUSINESSCARD_UPDATE>\r\n");
      out.write("</ROOT>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
